-- Q1. what is the total revenue generated by male vs. female customer.

SELECT "Gender", 
       SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select "Customer ID", "Purchase Amount (USD)"
from customer
where "Discount Applied" = 'Yes' and "Purchase Amount (USD)" >= (select avg ("Purchase Amount (USD)") from customer)

--Q3. WHich are the top 5 product with the highest average review rating?
SELECT "Item Purchased", 
       ROUND(AVG("Review Rating"::numeric),2) AS "Average Product Rating"
FROM customer
GROUP BY "Item Purchased"
ORDER BY AVG("Review Rating") DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT "Shipping Type", 
       ROUND(AVG("Purchase Amount (USD)"), 2) AS avg_purchase
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT "Subscription Status",
       COUNT("Customer ID") AS TOTAL_CUSTOMERS,
       ROUND(AVG("Purchase Amount (USD)"), 2) AS AVG_SPEND,
       ROUND(SUM("Purchase Amount (USD)"), 2) AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY "Subscription Status"
ORDER BY TOTAL_REVENUE DESC, AVG_SPEND DESC;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT "Item Purchased",
       ROUND(
           100.0 * SUM(
               CASE 
                   WHEN "Discount Applied" = 'Yes' 
                   THEN 1 
                   ELSE 0 
               END
           ) / COUNT(*), 
       2) AS DISCOUNT_RATE
FROM CUSTOMER
GROUP BY "Item Purchased"
ORDER BY DISCOUNT_RATE DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH CUSTOMER_TYPE AS (
    SELECT "Customer ID",
           "Previous Purchases",
           CASE
               WHEN "Previous Purchases" = 1 THEN 'New'
               WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS CUSTOMER_SEGMENT
    FROM CUSTOMER
)

SELECT CUSTOMER_SEGMENT,
       COUNT(*) AS "Number of Customers"
FROM CUSTOMER_TYPE
GROUP BY CUSTOMER_SEGMENT
ORDER BY "Number of Customers" DESC;


--Q8. What are the top 3 most purchased products within each category? 
WITH ITEM_COUNTS AS (
    SELECT "Category",
           "Item Purchased",
           COUNT("Customer ID") AS TOTAL_ORDERS,
           ROW_NUMBER() OVER (
               PARTITION BY "Category"
               ORDER BY COUNT("Customer ID") DESC
           ) AS ITEM_RANK
    FROM CUSTOMER
    GROUP BY "Category", "Item Purchased"
)

SELECT ITEM_RANK,
       "Category",
       "Item Purchased",
       TOTAL_ORDERS
FROM ITEM_COUNTS
WHERE ITEM_RANK <= 3
ORDER BY "Category", ITEM_RANK;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT "Subscription Status",
       COUNT("Customer ID") AS REPEAT_BUYERS,
       ROUND(
           100.0 * COUNT("Customer ID") / 
           SUM(COUNT("Customer ID")) OVER (), 2
       ) AS PERCENTAGE
FROM CUSTOMER
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

--Q10. What is the revenue contribution of each age group? 
SELECT "Age",
       SUM("Purchase Amount (USD)") AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY "Age"
ORDER BY TOTAL_REVENUE DESC;